// Pauper-legal land name sets for deterministic classification

// Bouncelands [10 cards]
// `legal:pauper is:bounceland`
export const BOUNCELAND = new Set([
  'Azorius Chancery',
  'Boros Garrison',
  'Dimir Aqueduct',
  'Golgari Rot Farm',
  'Gruul Turf',
  'Izzet Boilerworks',
  'Orzhov Basilica',
  'Rakdos Carnarium',
  'Selesnya Sanctuary',
  'Simic Growth Chamber'
])

// Artifact bi-color lands ("Bridge" cycle) [10 cards]
// `legal:pauper type:land type:artifact bridge`
export const ARTIFACT_BI = new Set([
  'Darkmoss Bridge',
  'Drossforge Bridge',
  'Goldmire Bridge',
  'Mistvault Bridge',
  'Razortide Bridge',
  'Rustvale Bridge',
  'Silverbluff Bridge',
  'Slagwoods Bridge',
  'Tanglepool Bridge',
  'Thornglint Bridge'
])

// Artifact mono-color lands (non-Bridge) [6 cards]
// `legal:pauper type:land type:artifact -bridge`
export const ARTIFACT_MONO = new Set([
  'Ancient Den',
  'Darksteel Citadel',
  'Great Furnace',
  'Seat of the Synod',
  'Tree of Tales',
  'Vault of Whispers'
])

// Gates [18 cards]
// `legal:pauper type:land type:gate`
export const GATES = new Set([
  'Azorius Guildgate',
  'Basilisk Gate',
  'Black Dragon Gate',
  'Boros Guildgate',
  'Citadel Gate',
  'Cliffgate',
  'Dimir Guildgate',
  'Gateway Plaza',
  'Golgari Guildgate',
  'Gruul Guildgate',
  'Heap Gate',
  'Izzet Guildgate',
  'Manor Gate',
  'Orzhov Guildgate',
  'Rakdos Guildgate',
  'Sea Gate',
  'Selesnya Guildgate',
  'Simic Guildgate'
])

// Fixer lands (any color, non-Gate)
// `(oracle:any oracle:color) type:land legal:pauper -type:gate`
export const FIXER = new Set([
  'Abandoned Outpost',
  'Archway Commons',
  'Bog Wreckage',
  'Captivating Cave',
  'Cave of Temptation',
  'Command Bridge',
  'Command Tower',
  'Conduit Pylons',
  'Crumbling Vestige',
  'Crystal Grotto',
  'Great Hall of the Citadel',
  'Hidden Grotto',
  'Holdout Settlement',
  'Opal Palace',
  'Painted Bluffs',
  'Path of Ancestry',
  'Public Thoroughfare',
  'Ravaged Highlands',
  'Rumble Arena',
  'Rupture Spire',
  'Seafloor Debris',
  'Shimmering Grotto',
  'Study Hall',
  'Survivors\' Encampment',
  'Timberland Ruins',
  'Transguild Promenade'
])

// Tapland bi-color (2-color identity, enters tapped)
// `legal:pauper type:land (o:enters o:tapped) id=2`
export const TAPLAND_BI = new Set([
  'Abandoned Campground',
  'Abraded Bluffs',
  'Airship Engine Room',
  'Alpine Meadow',
  'Arctic Treeline',
  'Azorius Chancery',
  'Azorius Guildgate',
  'Baron, Airship Kingdom',
  'Bleeding Woods',
  'Bloodfell Caves',
  'Blossoming Sands',
  'Boiling Rock Prison',
  'Boros Garrison',
  'Boros Guildgate',
  'Botanical Plaza',
  'Bristling Backwoods',
  'Cinder Barrens',
  'Contaminated Aquifer',
  'Creosote Heath',
  'Darkmoss Bridge',
  'Dimir Aqueduct',
  'Dimir Guildgate',
  'Dismal Backwater',
  'Drossforge Bridge',
  'Eroded Canyon',
  'Etched Cornfield',
  'Festering Gulch',
  'Foggy Bottom Swamp',
  'Forlorn Flats',
  'Forsaken Sanctuary',
  'Foul Orchard',
  'Geothermal Bog',
  'Glacial Floodplain',
  'Gohn, Town of Ruin',
  'Goldmire Bridge',
  'Golgari Guildgate',
  'Golgari Rot Farm',
  'Gongaga, Reactor Town',
  'Gruul Guildgate',
  'Gruul Turf',
  'Guadosalam, Farplane Gateway',
  'Haunted Mire',
  'Highland Forest',
  'Highland Lake',
  'Ice Tunnel',
  'Idyllic Beachfront',
  'Insomnia, Crown City',
  'Izzet Boilerworks',
  'Izzet Guildgate',
  'Jagged Barrens',
  'Jungle Hollow',
  'Kyoshi Village',
  'Lakeside Shack',
  'Lonely Arroyo',
  'Lorehold Campus',
  'Lush Oasis',
  'Meandering River',
  'Meditation Pools',
  'Mistvault Bridge',
  'Misty Palms Oasis',
  'Molten Tributary',
  'Murky Sewer',
  'Neglected Manor',
  'North Pole Gates',
  'Omashu City',
  'Ominous Asylum',
  'Orzhov Basilica',
  'Orzhov Guildgate',
  'Peculiar Lighthouse',
  'Prismari Campus',
  'Quandrix Campus',
  'Rabanastre, Royal City',
  'Racers\' Ring',
  'Radiant Grove',
  'Rakdos Carnarium',
  'Rakdos Guildgate',
  'Raucous Carnival',
  'Razortide Bridge',
  'Razortrap Gorge',
  'Rimewood Falls',
  'Rugged Highlands',
  'Rustvale Bridge',
  'Sacred Peaks',
  'Savage Mansion',
  'Scoured Barrens',
  'Selesnya Guildgate',
  'Selesnya Sanctuary',
  'Serpent\'s Pass',
  'Sharlayan, Nation of Scholars',
  'Silverbluff Bridge',
  'Silverquill Campus',
  'Simic Growth Chamber',
  'Simic Guildgate',
  'Sinister Hideout',
  'Skybridge Towers',
  'Slagwoods Bridge',
  'Snowfield Sinkhole',
  'Soured Springs',
  'Stone Quarry',
  'Strangled Cemetery',
  'Submerged Boneyard',
  'Suburban Sanctuary',
  'Sulfurous Mire',
  'Sun-Blessed Peak',
  'Sunlit Marsh',
  'Swiftwater Cliffs',
  'Tangled Islet',
  'Tanglepool Bridge',
  'Thornglint Bridge',
  'Thornwood Falls',
  'Timber Gorge',
  'Tramway Station',
  'Tranquil Cove',
  'Tranquil Expanse',
  'Treno, Dark City',
  'University Campus',
  'Vector, Imperial Capital',
  'Volatile Fjord',
  'Waterfront District',
  'Wind-Scarred Crag',
  'Windurst, Federation Center',
  'Witherbloom Campus',
  'Wooded Ridgeline',
  'Woodland Chasm',
  'Woodland Stream'
])

// Tapland mono-color (1-color identity, enters tapped)
// `legal:pauper type:land (o:enters o:tapped) id=1`
export const TAPLAND_MONO = new Set([
  'Abandoned Outpost',
  'Barren Moor',
  'Black Dragon Gate',
  'Bog Wreckage',
  'Bojuka Bog',
  'Citadel Gate',
  'Cliffgate',
  'Desert of the Fervent',
  'Desert of the Glorified',
  'Desert of the Indomitable',
  'Desert of the Mindful',
  'Desert of the True',
  'Drifting Meadow',
  'Dwarven Mine',
  'Fertile Thicket',
  'Forgotten Cave',
  'Gingerbread Cabin',
  'Halimar Depths',
  'Hickory Woodlot',
  'Hidden Cataract',
  'Hidden Courtyard',
  'Hidden Necropolis',
  'Hidden Nursery',
  'Hidden Volcano',
  'Idyllic Grange',
  'Kabira Crossroads',
  'Khalni Garden',
  'Lonely Sandbar',
  'Looming Spires',
  'Manor Gate',
  'Mortuary Mire',
  'Peat Bog',
  'Piranha Marsh',
  'Polluted Mire',
  'Ravaged Highlands',
  'Remote Farm',
  'Remote Isle',
  'Sandstone Bridge',
  'Sandstone Needle',
  'Saprazzan Skerry',
  'Seafloor Debris',
  'Sea Gate',
  'Secluded Steppe',
  'Sejiri Steppe',
  'Skyline Cascade',
  'Slippery Karst',
  'Smoldering Crater',
  'Smoldering Spires',
  'Soaring Seacliff',
  'Teetering Peaks',
  'The Autonomous Furnace',
  'The Dross Pits',
  'The Fair Basilica',
  'The Hunter Maze',
  'The Surgical Bay',
  'Thriving Bluff',
  'Thriving Grove',
  'Thriving Heath',
  'Thriving Isle',
  'Thriving Moor',
  'Timberland Ruins',
  'Tranquil Thicket',
  'Turntimber Grove',
  'Witch\'s Cottage'
])

// Fetch lands (search for lands) [28 cards]
// `legal:pauper type:land (oracle:search)`
export const FETCH = new Set([
  'Bant Panorama',
  'Bountiful Landscape',
  'Brokers Hideout',
  'Cabaretti Courtyard',
  'Contaminated Landscape',
  'Deceptive Landscape',
  'Escape Tunnel',
  'Esper Panorama',
  'Evolving Wilds',
  'Foreboding Landscape',
  'Grixis Panorama',
  'Jund Panorama',
  'Maestros Theater',
  'Naya Panorama',
  'Obscura Storefront',
  'Perilous Landscape',
  'Promising Vein',
  'Riveteers Overlook',
  'Seething Landscape',
  'Shattered Landscape',
  'Sheltering Landscape',
  'Shire Terrace',
  'Terminal Moraine',
  'Terramorphic Expanse',
  'Tranquil Landscape',
  'Twisted Landscape',
  'Vibrant Cityscape',
  'Warped Landscape'
])

// Basic lands
export const BASIC = new Set([
  'Plains',
  'Island',
  'Swamp',
  'Mountain',
  'Forest',
  'Wastes',
  'Snow-Covered Plains',
  'Snow-Covered Island',
  'Snow-Covered Swamp',
  'Snow-Covered Mountain',
  'Snow-Covered Forest'
])
